require conf/distro/poky.conf

DISTRO = "bmo"
DISTRO_NAME = "bmo (Test Distro)"
MAINTAINER = "Youssef <yousseflkashef000@gmail.com>"

DISTRO_FEATURES:append = " systemd usrmerge pam opengl"

IMAGE_FEATURES:append = " splash hwcodecs ssh-server-dropbear"


VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""

DISTRO_FEATURES_BACKFILL += " sysvinit"


LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"