# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-hey_man"
BBFILE_PATTERN_meta-hey_man = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-hey_man = "6"

LAYERDEPENDS_meta-hey_man = "core"
LAYERSERIES_COMPAT_meta-hey_man = "scarthgap"
